### ISSUE TITLE
XMLTV issue

### ISSUE THREAD

**Issue by badtou** [fHDHR/fHDHR_PlutoTV#130]
The XMLTV file returned is massive which causes Plex to crash, and the ChannelsDVR guide to display only the first few programs for a channels with the remaining 6 hours showing as not available.
Investigating I found that the current file of 40 mb nearly 8 times the size of the file created by Jon Maddox's PlutoTV Docker image.

**Comment by deathbybandaid** [comment]
Care to elaborate?
